### ISSUE TITLE
Slow training for zero num_worker?

### ISSUE THREAD

**Issue by RyanLiut** [SapienzaNLP/esc#2]
Hi,

Thank you for the code! I wonder if there is something wrong when I am running the code: it is so slow, and one epoch consumed ~2h. I used the Tesla V100 server. But the paper reported only about 5 hours for training. Btw, I have to set the num_workers to 0 since when I increase that number larger than 1, then it has another error saying wordnet can't search for some keys (Idk why a key error could happen...)

Thank you!

**Comment by edobobo** [comment]
Hi,

The problem is that the "gloss_noise" implementation in this repository is rather slow, and you cannot set num_workers greater than 0 because the nltk interface for wordnet does not let you access it in parallel. There are three possible solutions:

1) You disable gloss_noise.
2) You implement a faster version of gloss_noise.
3) You wait a little bit since we are planning to release a more efficient version of this project to meet industry standards.

**Comment by RyanLiut** [comment]
Got it. Thank you very much!

**Comment by edobobo** [comment]
You're welcome :)
